### ISSUE TITLE
0.5.1, tf 2.11 error for accuoptimizer

### ISSUE THREAD

**Issue by AlexanderYaroshevichIAC** [andreped/GradientAccumulator#105]
/lib/python3.8/site-packages/gradient_accumulator/accumulators.py", line 247, in _create_slots
        self._optimizer._create_slots(var_list=var_list)

    AttributeError: 'SGD' object has no attribute '_create_slots'

**Comment by AlexanderYaroshevichIAC** [comment]
using legacy sgd doesn't work either. 
```
/python3.8/site-packages/gradient_accumulator/accumulators.py", line 460, in _apply
        accum_gradient.sparse_read(indices),

    AttributeError: 

```
That is the full attribute error: no other details of the error is printed

**Comment by AlexanderYaroshevichIAC** [comment]
master branch doesn't work either with the same error

**Comment by andreped** [comment]
We are performing unit tests for every commit and release which tests for situations like this. Hence, it should work. We explicitly test with `tensorflow==2.12` (see [here](https://github.com/andreped/GradientAccumulator/blob/main/.github/workflows/test.yml#L53)). I also ran a test now locally and it worked fine with `tensorflow==2.13`. The test I ran is available [here](https://github.com/andreped/GradientAccumulator/blob/main/tests/test_optimizer_wrapper.py#L48).

For `tf>=2.10`, you have to use the legacy optimizer, which I see that you also tried, which prompted a different issue.

As you got some error with the `sparse_read()`, I assume this might be due to the use of some transformer architecture or similar which uses the `tf.keras.layers.Embedding()` layer. We have a unit test for that as well [here](https://github.com/andreped/GradientAccumulator/blob/main/tests/test_sparse_optimizer.py#L73). I just tried running it now, and I could not reproduce the issue. However, note that for sparse operators, we do not yet yield expected results as for regular ops when using gradient accumulation.

Perhaps you could try running these unit tests on your local setup to see if they work on your end? As a sanity check. To run them for instance run:
```
pytest -v tests/test_sparse_optimizer.py
```

To debug this further, it would be nice to know a little bit more of what you are trying to do. Are you trying to train a transformer architecture in a distributed setting with multiple GPU, hence why you wanted to use the Optimizer wrapper? For single-GPU use, the model wrapper works way better, IMO - at least we have benchmarked and tested that the most.

**Comment by AlexanderYaroshevichIAC** [comment]
Trying to run 'tinyvit.TinyViT_21M' from https://github.com/leondgarse/keras_cv_attention_models using 2x2080ti. Tried with single gpu the same error occurs. Tried efficientnet from kecam also got the same error. Tried efficientnet and it's working fine. So I guess the transformer is the issue

**Comment by andreped** [comment]
Oh, ok, thats interesting. There is likely one or more layers in the network we have yet to test and add support for.

Could you make a simple reproducible script/gist, and I can debug this further and potentially add a fix? :)

**Comment by AlexanderYaroshevichIAC** [comment]
Sorry, Unfortunately I'm quite busy these days :(

**Comment by andreped** [comment]
Could you try using the model wrapper instead, just as a sanity check? Just reduce the batch size by half to test. I just wanted to know if this only impacted the optimizer wrapper.

The only real benefit of having multiple GPUs, if you can fit the model on a single GPU, is improved training runtime. You can still increase the batch size using the model wrapper.

**Comment by andreped** [comment]
Closing as @AlexanderYaroshevichIAC failed to provide a script to reproduce the issue.

Feel free to reopen the issue, if you have a gist I can use, @AlexanderYaroshevichIAC :]
